//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.26 at 04:26:50 PM PDT 
//


package org.soter.rbac.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.soter.rbac.model package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Rbac_QNAME = new QName("http://geronimo.apache.org/xml/ns/rbac-xml", "rbac");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.soter.rbac.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoleRefType }
     * 
     */
    public RoleRefType createRoleRefType() {
        return new RoleRefType();
    }

    /**
     * Create an instance of {@link PermissionType }
     * 
     */
    public PermissionType createPermissionType() {
        return new PermissionType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link UserRoleType }
     * 
     */
    public UserRoleType createUserRoleType() {
        return new UserRoleType();
    }

    /**
     * Create an instance of {@link RbacType }
     * 
     */
    public RbacType createRbacType() {
        return new RbacType();
    }

    /**
     * Create an instance of {@link ScopeType }
     * 
     */
    public ScopeType createScopeType() {
        return new ScopeType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RbacType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://geronimo.apache.org/xml/ns/rbac-xml", name = "rbac")
    public JAXBElement<RbacType> createRbac(RbacType value) {
        return new JAXBElement<RbacType>(_Rbac_QNAME, RbacType.class, null, value);
    }

}
