//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.26 at 04:15:25 PM PDT 
//


package org.soter.rbac.model;

import java.io.Serializable;
import java.security.Permission;
import java.util.HashMap;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.apache.xbean.recipe.ObjectRecipe;
import org.apache.xbean.recipe.Option;


/**
 * <p>Java class for permissionType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="permissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="permission-id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="actions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "permissionType", propOrder = {
        "permissionId",
        "clazz",
        "name",
        "actions"
        })
public class PermissionType
        implements Serializable, Keyable<String> {

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "permission-id", required = true)
    protected String permissionId;
    @XmlElement(name = "class", required = true)
    protected String clazz;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String actions;

    @XmlTransient
    private Permission permission;
    @XmlTransient
    private ScopeType scope;

    public PermissionType() {
    }

    public PermissionType(PermissionType original, ScopeType owner) {
        permissionId = original.permissionId;
        clazz = original.clazz;
        name = original.name;
        actions = original.actions;
        permission = original.permission;
        scope = owner;
    }

    /**
     * Gets the value of the permissionId property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPermissionId() {
        return permissionId;
    }

    public String getKey() {
        return getPermissionId();
    }

    /**
     * Sets the value of the permissionId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPermissionId(String value) {
        this.permissionId = value;
    }

    /**
     * Gets the value of the clazz property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClazz(String value) {
        permission = null;
        this.clazz = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        permission = null;
        this.name = value;
    }

    /**
     * Gets the value of the actions property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setActions(String value) {
        permission = null;
        this.actions = value;
    }

    public void start(ScopeType scope, ClassLoader cl) {
        this.scope = scope;
        Map props = new HashMap(2);
        props.put("name", name);
        props.put("actions", actions);
        ObjectRecipe recipe = new ObjectRecipe(clazz, props);
        recipe.setConstructorArgNames(new String[] {"name", "actions"});
        permission = (Permission) recipe.create(cl);
    }

    public Permission getPermission() {
        return permission;
    }

    public ScopeType getScope() {
        return scope;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        PermissionType that = (PermissionType) o;

        if (actions != null ? !actions.equals(that.actions) : that.actions != null) return false;
        if (clazz != null ? !clazz.equals(that.clazz) : that.clazz != null) return false;
        if (name != null ? !name.equals(that.name) : that.name != null) return false;
        if (permissionId != null ? !permissionId.equals(that.permissionId) : that.permissionId != null) return false;

        return true;
    }

    public int hashCode() {
        int result;
        result = (permissionId != null ? permissionId.hashCode() : 0);
        result = 31 * result + (clazz != null ? clazz.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (actions != null ? actions.hashCode() : 0);
        result = 31 * result + (permission != null ? permission.hashCode() : 0);
        result = 31 * result + (scope != null ? scope.hashCode() : 0);
        return result;
    }
}
